# Generated by Django 2.2.7 on 2024-06-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240622_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='data_lancamento',
        ),
    ]
