# Generated by Django 2.2.7 on 2024-06-27 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_lancamento_data_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Som',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem_som', models.ImageField(blank=True, null=True, upload_to='sons/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Artista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Lancamento',
        ),
    ]
