# Generated by Django 5.1.2 on 2024-11-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_artista_id_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='som',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='som',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.DeleteModel(
            name='Som',
        ),
    ]
